Repository WordPress/openverse-api, pull requests merged in 2021-10, with the labels that each got.

#210 Separate `CURATED` and `CULTURAL_INSTITUTION` authority types
  ingestion_server/ingestion_server/authority.py
Labels: ✨ goal: improvement, 💻 aspect: code

#256 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_prs.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#202 Refactor the use of environment variables
  .github/workflows/integration-tests.yml
  README.md
  docker-compose.yml
  ingestion_server/Pipfile
  ingestion_server/Pipfile.lock
  ingestion_server/README.md
  ingestion_server/config/supervisord.conf
  ingestion_server/env.docker
  ingestion_server/env.template
  ingestion_server/gunicorn.conf.py
  ingestion_server/ingestion_server/api.py
  ingestion_server/ingestion_server/cleanup.py
  ingestion_server/ingestion_server/distributed_reindex_scheduler.py
  ingestion_server/ingestion_server/elasticsearch_models.py
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/ingestion_server/indexer_worker.py
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/state.py
  ingestion_server/ingestion_server/tasks.py
  ingestion_server/test/unit_tests.py
  initialization.PNG
  justfile
  local_api_documentation.PNG
  localhost_request.PNG
  openverse_api/Pipfile
  openverse_api/Pipfile.lock
  openverse_api/README.md
  openverse_api/catalog/api/serializers/link_serializers.py
  openverse_api/catalog/settings.py
  openverse_api/env.docker
  openverse_api/env.template
  openverse_api/test/run_test.sh
  postgres/env.docker
  readme_assets/api_redoc.png
  readme_assets/howitworks.png
  readme_assets/system_architecture.png
Labels: 🌟 goal: addition, 🤖 aspect: dx

#264 Removing redundant `test/README`
  openverse_api/test/README
Labels: ✨ goal: improvement, 📄 aspect: text

#263 Clean up GitHub Actions workflows
  .github/workflows-disabled/IssueAndPR.yml
  .github/workflows-disabled/README.md
  .github/workflows/integration_tests.yml
  .github/workflows/release_drafter.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#266 Add file type information to the Django models
  load_sample_data.sh
  openverse_api/catalog/api/migrations/0038_filetypes.py
  openverse_api/catalog/api/models/audio.py
  openverse_api/catalog/api/models/image.py
  openverse_api/catalog/api/models/media.py
  openverse_api/catalog/api/models/mixins.py
Labels: 🌟 goal: addition, 💻 aspect: code

#268 Add just recipe to wait for stack startup
  .github/workflows/integration_tests.yml
  .gitignore
  docker-compose.yml
  justfile
Labels: 🛠 goal: fix, 🤖 aspect: dx

#330 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_ping.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx
