Repository WordPress/openverse-api, pull requests merged in 2021-12, with the labels that each got.

#346 Production deployment files
  ingestion_server/README.md
  ingestion_server/docker-compose.yml
  justfile
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx

#380 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_ping.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#394 Fix page_size setting for related media
  openverse_api/catalog/api/views/media_views.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#398 Check if value is numeric before converting to int
  openverse_api/catalog/api/utils/pagination.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#408 Add docker volumes for local development
  docker-compose.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#415 Rename indices back to original during data refresh
  ingestion_server/README.md
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/queries.py
  ingestion_server/mock_schemas/audio.sql
  ingestion_server/mock_schemas/image.sql
  ingestion_server/test/gen_integration_compose.py
  ingestion_server/test/integration_test.py
  ingestion_server/test/mock_schemas/README.md
  ingestion_server/test/mock_schemas/audio.sql
  ingestion_server/test/mock_schemas/audioset.sql
  ingestion_server/test/mock_schemas/image.sql
  ingestion_server/test/run_test.sh
  justfile
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code, python

#422 Make API tests pass and reduce flakiness
  analytics/tests.py
  openverse_api/catalog/api/utils/validate_images.py
  openverse_api/test/auth_test.py
  openverse_api/test/dead_link_filter_test.py
  openverse_api/test/v1_integration_test.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#426 Set tldextract cache to writable directory
  ingestion_server/Dockerfile
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#434 Add kwarg 'child' required by `seriaizers.ListField`
  openverse_api/catalog/api/serializers/audio_serializers.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#435 Add hook to clean up YAML files
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/integration_tests.yml
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_label_check.yml
  .github/workflows/pr_ping.yml
  .pre-commit-config.yaml
  analytics/docs/swagger.yaml
  docker-compose.yml
  ingestion_server/docker-compose.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#433 Remove Dependabot for Docker and reduce frequency
  .github/dependabot.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement
