Repository WordPress/openverse-api, pull requests merged in 2021-11, with the labels that each got.

#356 Protect foreign key constraint between `imagelist_images` and `imagelist`
  ingestion_server/test/unit_test.py
  openverse_api/catalog/api/migrations/0001_initial.py
  openverse_api/catalog/api/migrations/0002_auto_20180723_1737.py
  openverse_api/catalog/api/migrations/0003_image_view_count.py
Labels: 🛠 goal: fix, 💻 aspect: code

#358 Add migration for removing ShortendLink
  openverse_api/catalog/api/migrations/0043_delete_shortenedlink.py
Labels: 🛠 goal: fix, 💻 aspect: code

#370 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_label_check.yml
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#371 Add priority labels to Dependabot PRs
  .github/dependabot.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#365 Include deleted & mature existence checks when updating indices
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/test/integration_test.py
Labels: 🛠 goal: fix, 💻 aspect: code

#366 Add gunicorn to project requirements
  openverse_api/Pipfile
  openverse_api/Pipfile.lock
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
