Repository WordPress/openverse-api, pull requests merged in 2021-09, with the labels that each got.

#197 Update page_count calculation to fix off-by-one issue
  openverse-api/catalog/api/controllers/search_controller.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#209 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/pr_label_check.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#211 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/new_prs.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#216 Add Dependabot for ingestion API
  .github/dependabot.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#194 Clean up API codebase by using idiomatic DRF and removing boilerplate
  openverse-api/catalog/api/docs/README.md
  openverse-api/catalog/api/docs/__init__.py
  openverse-api/catalog/api/docs/audio_docs.py
  openverse-api/catalog/api/docs/image_docs.py
  openverse-api/catalog/api/docs/media_docs.py
  openverse-api/catalog/api/examples/__init__.py
  openverse-api/catalog/api/examples/audio_requests.py
  openverse-api/catalog/api/examples/audio_responses.py
  openverse-api/catalog/api/examples/image_requests.py
  openverse-api/catalog/api/examples/image_responses.py
  openverse-api/catalog/api/serializers/audio_serializers.py
  openverse-api/catalog/api/serializers/error_serializers.py
  openverse-api/catalog/api/serializers/image_serializers.py
  openverse-api/catalog/api/serializers/media_serializers.py
  openverse-api/catalog/api/serializers/provider_serializers.py
  openverse-api/catalog/api/utils/exceptions.py
  openverse-api/catalog/api/utils/pagination.py
  openverse-api/catalog/api/views/audio_views.py
  openverse-api/catalog/api/views/image_views.py
  openverse-api/catalog/api/views/media_views.py
  openverse-api/catalog/settings.py
  openverse-api/catalog/urls/__init__.py
  openverse-api/catalog/urls/audio.py
  openverse-api/catalog/urls/images.py
  openverse-api/catalog/urls/swagger.py
  openverse-api/test/audio_integration_test.py
  openverse-api/test/backwards_compat_test.py
  openverse-api/test/examples_test.py
  openverse-api/test/image_integration_test.py
  openverse-api/test/media_integration.py
  openverse-api/test/v1_integration_test.py
Labels: ✨ goal: improvement, 🤖 aspect: dx

#222 stop tracking of .idea folder or directory
  .idea/dictionaries/alden.xml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#233 Fix circular import of OpenLedgerModel
  openverse-api/catalog/api/models/__init__.py
Labels: 🛠 goal: fix, 💻 aspect: code

#243 🔄 Synced file(s) with WordPress/openverse
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🛠 goal: fix, 🤖 aspect: dx

#237 Improved lint check speed
  .github/workflows/integration-tests.yml
Labels: 🤖 aspect: dx, 🧰 goal: internal improvement

#244 Organise and document `justfile`
  .github/workflows/integration-tests.yml
  README.md
  docker-compose.yml
  ingestion_server/README.md
  ingestion_server/env.docker
  ingestion_server/env.template
  justfile
  openverse_api/README.md
  openverse_api/env.docker
  openverse_api/env.template
  postgres/env.docker
Labels: 🤖 aspect: dx, 🧰 goal: internal improvement
