Repository WordPress/openverse-api, pull requests merged in 2022-08, with the labels that each got.

#819 Use force_orphan to prevent gh-pages branch history from ballooning repo size
  .github/workflows/ci_cd.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#840 Run init as part of just recreate
  justfile
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#841 Use sudo when removing preview folders
  .github/workflows/ci_cd.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#842 Ignore DisallowedHosts logs from Sentry
  api/catalog/settings.py
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#852 Selectively revert suspect commits causing API instability
  api/catalog/api/controllers/elasticsearch/__init__.py
  api/catalog/api/controllers/elasticsearch/related.py
  api/catalog/api/controllers/elasticsearch/search.py
  api/catalog/api/controllers/elasticsearch/stats.py
  api/catalog/api/controllers/elasticsearch/utils.py
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/utils/pagination.py
  api/catalog/api/views/media_views.py
  api/test/audio_integration_test.py
  load_sample_data.sh
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#861 Run black before flake8 in pre-commit hook
  .pre-commit-config.yaml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#860 Remove the SENTRY_DSN value
  api/catalog/settings.py
  api/env.docker
  api/env.template
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#859 Limit page depth of searches
  api/Pipfile
  api/Pipfile.lock
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/utils/pagination.py
  api/test/dead_link_filter_test.py
  api/test/unit/controllers/test_search_controller.py
Labels: 🟥 priority: critical, ✨ goal: improvement, 💻 aspect: code

#869 Fix syntax error in sample data load script
  justfile
  load_sample_data.sh
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#865 Only backfill dead links if at least one on first page was not dead
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/utils/validate_images.py
  api/test/dead_link_filter_test.py
Labels: 🟥 priority: critical, ✨ goal: improvement, 💻 aspect: code

#822 Leave a comment and add `migrations` on issues that have migrations reminding the author to rebase before merging
  .github/auto-label.json
  .github/workflows/ci_cd.yml
  .github/workflows/migration_safety_warning.yml
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement, migrations

#878 Extend valid link cache time to 30 days and make cache expiration times minimally configurable
  api/catalog/api/utils/validate_images.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#882 Updates handbook broken link
  README.md
Labels: 🚦 status: awaiting triage

#864 Add throttling classes for thumbnail endpoint
  api/catalog/api/utils/throttle.py
  api/catalog/api/views/image_views.py
  api/catalog/settings.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#884 Prevent tests from making network requests for link validation and fix potentially non-unique factory props
  api/test/audio_integration_test.py
  api/test/factory/faker.py
  api/test/factory/models/media.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#875 Do not 500 when upstream provider is unavailable
  api/catalog/api/views/media_views.py
  api/test/factory/models/image.py
  api/test/unit/views/media_views_test.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#862 Define user to be used to run container process
  docker-compose.yml
  justfile
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#844 Remap ports to the non-conflicting range
  .github/workflows/ci_cd.yml
  api/README.md
  api/catalog/settings.py
  api/docs/guides/quickstart.md
  api/docs/guides/test.md
  api/run.sh
  docker-compose.yml
  ingestion_server/test/gen_integration_compose.py
  ingestion_server/test/test_constants.py
  justfile
  nginx/templates/web.conf.template
Labels: 🟨 priority: medium, ✨ goal: improvement, 🤖 aspect: dx

#886 Add `just dc` recipe
  api/docs/guides/quickstart.md
  justfile
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#877 Add `User-Agent` header to all outbound requests coming from the API
  api/catalog/api/utils/validate_images.py
  api/catalog/api/utils/watermark.py
  api/catalog/api/utils/waveform.py
  api/catalog/api/views/image_views.py
  api/catalog/api/views/media_views.py
  api/catalog/settings.py
  api/test/audio_integration_test.py
  api/test/factory/models/media.py
  api/test/factory/sample-audio-info.json
  api/test/factory/sample-audio.mp3
  api/test/factory/sample-image-info.json
  api/test/factory/sample-image.jpg
  api/test/image_integration_test.py
  api/test/media_integration.py
  api/test/unit/utils/validate_images_test.py
  api/test/unit/utils/watermark_test.py
  api/test/unit/utils/waveform_test.py
  api/test/unit/views/image_views_test.py
  api/test/unit/views/media_views_test.py
  docker-compose.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#890 Update CODEOWNERS to use new API team
  .github/CODEOWNERS
Labels: 🚦 status: awaiting triage

#870 Add comments to pagination and dead link mask and validation
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/utils/validate_images.py
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#888 Ensure that license URL is not blank
  api/catalog/api/serializers/media_serializers.py
  api/test/unit/serializers/media_serializers_test.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#806 Add validate spec command
  .github/workflows/ci_cd.yml
  .gitignore
  api/Pipfile
  api/Pipfile.lock
  api/catalog/api/views/oauth2_views.py
  api/catalog/management/commands/validateopenapischema.py
  api/catalog/settings.py
  api/catalog/urls/__init__.py
  api/catalog/urls/auth_tokens.py
  api/catalog/urls/swagger.py
  justfile
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#891 Add unit tests for _paginate_with_dead_link_mask
  api/catalog/api/controllers/search_controller.py
  api/test/unit/controllers/test_search_controller.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#829 Use the database category value for Elasticsearch model
  api/catalog/api/models/image.py
  api/catalog/api/serializers/image_serializers.py
  ingestion_server/ingestion_server/categorize.py
  ingestion_server/ingestion_server/elasticsearch_models.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code, data normalization
