Repository WordPress/openverse-api, pull requests merged in 2022-06, with the labels that each got.

#741 Revert "Refactor search controller for consistency and clarity"
  api/catalog/api/controllers/elasticsearch/__init__.py
  api/catalog/api/controllers/elasticsearch/related.py
  api/catalog/api/controllers/elasticsearch/search.py
  api/catalog/api/controllers/elasticsearch/stats.py
  api/catalog/api/controllers/elasticsearch/utils.py
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/models/audio.py
  api/catalog/api/models/image.py
  api/catalog/api/models/media.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/utils/pagination.py
  api/catalog/api/views/media_views.py
  api/catalog/settings.py
  load_sample_data.sh
Labels: 🚦 status: awaiting triage

#744 Update example image to one that passes dead link filter
  api/catalog/api/examples/image_requests.py
  api/catalog/api/examples/image_responses.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#750 Ensure that the docs cleanup step only runs on PRs that have permission
  .github/workflows/pr_closed.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#753 Log each index & constraint step
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/test/integration_test.py
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#727 Make thumbnail link null for audio files without artwork
  api/catalog/api/serializers/audio_serializers.py
  api/test/audio_integration_test.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#755 Limit `page_size` to 20 for unauthenticated requests
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/views/media_views.py
  api/test/auth_test.py
  api/test/dead_link_filter_test.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#756 Prevent thumbnail timeout
  api/catalog/api/views/media_views.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#763 Reduce throttling threshold, allow throttling config via env vars
  api/catalog/api/docs/README.md
  api/catalog/settings.py
Labels: 🟥 priority: critical, ✨ goal: improvement, 💻 aspect: code

#765 Make thumbnail link null for in audio detail endpoint when it doesn't exist
  api/catalog/api/serializers/audio_serializers.py
  api/test/audio_integration_test.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#766 Fix invalid UUID breaking related images query
  api/catalog/api/views/media_views.py
  api/test/api_live_integration.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#768 Remove one-time-use command
  api/catalog/management/commands/resendoauthverification.py
  api/test/unit/management/commands/resendoauthverification_test.py
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#767 License validation does not work correctly for non-lower-case strings #740
  api/catalog/api/serializers/media_serializers.py
  api/test/audio_integration_test.py
  api/test/image_integration_test.py
  api/test/media_integration.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code
