Repository WordPress/openverse-api, pull requests merged in 2022-05, with the labels that each got.

#673 Override `to_representation` instead of setting default
  api/catalog/api/serializers/media_serializers.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#633 Configure isort, rearrange imports and remove circular dependency
  .isort.cfg
  .pre-commit-config.yaml
  api/catalog/api/admin.py
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/docs/audio_docs.py
  api/catalog/api/docs/image_docs.py
  api/catalog/api/models/audio.py
  api/catalog/api/models/image.py
  api/catalog/api/models/media.py
  api/catalog/api/models/models.py
  api/catalog/api/models/oauth.py
  api/catalog/api/serializers/audio_serializers.py
  api/catalog/api/serializers/image_serializers.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/serializers/oauth2_serializers.py
  api/catalog/api/serializers/provider_serializers.py
  api/catalog/api/utils/oauth2_helper.py
  api/catalog/api/utils/pagination.py
  api/catalog/api/utils/scheduled_tasks.py
  api/catalog/api/utils/throttle.py
  api/catalog/api/utils/validate_images.py
  api/catalog/api/views/audio_views.py
  api/catalog/api/views/image_views.py
  api/catalog/api/views/media_views.py
  api/catalog/api/views/oauth2_views.py
  api/catalog/management/commands/generatewaveforms.py
  api/catalog/settings.py
  api/catalog/urls/__init__.py
  api/catalog/urls/auth_tokens.py
  api/catalog/urls/swagger.py
  api/catalog/wsgi.py
  api/test/api_live_integration.py
  api/test/auth_test.py
  api/test/factory/models/audio.py
  api/test/factory/models/media.py
  api/test/factory/models/oauth2.py
  api/test/unit/management/commands/generatewaveforms_test.py
  api/test/unit/models/audio_test.py
  api/test/unit/utils/test_help_text.py
  api/test/unit/utils/throttle_test.py
  api/test/v1_integration_test.py
Labels: 🟩 priority: low, 🚧 status: blocked, 🤖 aspect: dx, 🧰 goal: internal improvement

#677 Add DEFAULT_FROM_EMAIL setting handling
  api/catalog/settings.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#681 Add HTTPS doc to table of contents, fix warning
  api/docs/guides/index.md
  api/docs/guides/publish.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#678 Update Terms of Service
  LICENSE
  api/catalog/urls/swagger.py
  api/docs/index.md
  api/docs/terms_of_service.md
  api/terms_of_service.html
Labels: 🟧 priority: high, ✨ goal: improvement, 📄 aspect: text

#679 Add developer docs preview deployments
  .github/workflows/ci_cd.yml
  .github/workflows/pr_closed.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#682 Defer ThrottledApplication reference
  api/catalog/api/utils/oauth2_helper.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#683 Do not run docs preview action on main branch
  .github/workflows/ci_cd.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#686 Only run the docs preview on pull requests
  .github/workflows/ci_cd.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#688 Reverse indexing order for audio and images
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/tasks.py
  load_sample_data.sh
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#690 Add 3D model type to constants
  ingestion_server/ingestion_server/constants/media_types.py
Labels: 🚦 status: awaiting triage

#685 Refactor license constants and utils
  api/catalog/api/constants/licenses.py
  api/catalog/api/examples/audio_responses.py
  api/catalog/api/examples/image_responses.py
  api/catalog/api/licenses.py
  api/catalog/api/models/media.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/utils/attribution.py
  api/catalog/api/utils/licenses.py
  api/test/api_live_integration.py
  api/test/factory/models/media.py
  api/test/unit/utils/attribution_test.py
  api/test/v1_integration_test.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#694 Add command to resend verification emails
  api/catalog/management/commands/resendoauthverification.py
  api/test/factory/models/oauth2.py
  api/test/unit/management/commands/resendoauthverification_test.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#648 Use `::` over `cast` in audioset_view
  load_sample_data.sh
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#705 Add AudioReports to the Django admin
  api/catalog/api/admin.py
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code, 🔧 tech: django

#699 Refactor search controller for consistency and clarity
  api/catalog/api/controllers/elasticsearch/__init__.py
  api/catalog/api/controllers/elasticsearch/related.py
  api/catalog/api/controllers/elasticsearch/search.py
  api/catalog/api/controllers/elasticsearch/stats.py
  api/catalog/api/controllers/elasticsearch/utils.py
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/models/audio.py
  api/catalog/api/models/image.py
  api/catalog/api/models/media.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/utils/pagination.py
  api/catalog/api/views/media_views.py
  api/catalog/settings.py
  load_sample_data.sh
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#723 Fix issue due to `page_query_param` not being a string
  .github/workflows/ci_cd.yml
  api/catalog/custom_auto_schema.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code
