Repository WordPress/openverse-api, pull requests merged in 2022-01, with the labels that each got.

#444 🔄 Synced file(s) with WordPress/openverse
  .github/release-drafter.yml
  .github/release_drafter.yml
  .github/workflows/draft_release.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#411 Add sentry
  .gitignore
  justfile
  openverse_api/Pipfile
  openverse_api/Pipfile.lock
  openverse_api/catalog/settings.py
  openverse_api/env.template
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement

#429 Reuse images across jobs
  .github/workflows/integration_tests.yml
  analytics/Dockerfile
  analytics/Pipfile
  analytics/Pipfile.lock
  docker-compose.yml
  ingestion_server/Dockerfile
  ingestion_server/Dockerfile_worker
  ingestion_server/Pipfile
  ingestion_server/Pipfile.lock
  ingestion_server/config/supervisord.conf
  justfile
  load_sample_data.sh
  openverse_api/Dockerfile
  openverse_api/Pipfile
  openverse_api/Pipfile.lock
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#437 Publish images via a comprehensive CI + CD workflow
  .github/workflows/ci_cd.yml
  ingestion_server/README.md
  ingestion_server/docker-compose.yml
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#449 Deleted all instances of publish_release.sh
  ingestion_server/publish_release.sh
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#421 Data refresh slack notifications
  ingestion_server/README.md
  ingestion_server/ingestion_server/api.py
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/slack.py
  ingestion_server/ingestion_server/tasks.py
  ingestion_server/test/env.integration
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code, 🐍 tech: python

#454 Use event_name over event for publish conditional
  .github/workflows/ci_cd.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#427 Setup Sphinx for developer-docs
  README.md
  api/Pipfile
  api/Pipfile.lock
  api/README.md
  api/catalog/api/docs/README.md
  api/catalog/urls/swagger.py
  api/docs/_static/_css/brand.css
  api/docs/_static/api_redoc.png
  api/docs/_templates/page.html
  api/docs/_templates/sidebar/brand.html
  api/docs/conf.py
  api/docs/guides/deploy.md
  api/docs/guides/document.md
  api/docs/guides/index.md
  api/docs/guides/quickstart.md
  api/docs/guides/run.md
  api/docs/guides/test.md
  api/docs/index.md
  api/docs/reference/api/constants.rst
  api/docs/reference/api/controllers.rst
  api/docs/reference/api/docs.rst
  api/docs/reference/api/examples.rst
  api/docs/reference/api/index.rst
  api/docs/reference/api/models.rst
  api/docs/reference/api/serializers.rst
  api/docs/reference/api/utils.rst
  api/docs/reference/api/views.rst
  api/docs/reference/index.rst
  api/docs/reference/urls.rst
  docker-compose.yml
  justfile
  readme_assets/api_redoc.png
Labels: 🟩 priority: low, 🌟 goal: addition, 📄 aspect: text

#462 Update the Python label that Dependabot uses
  .github/dependabot.yml
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#464 Improve ingestion server slack alerts
  ingestion_server/ingestion_server/tasks.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#461 Update CI + CD pipeline to deploy Sphinx docs to GH pages
  .github/workflows/ci_cd.yml
  justfile
Labels: 🟨 priority: medium, 🌟 goal: addition, 📄 aspect: text

#457 Override default RELATIVE_UPSTREAM_DB_* vars for integration tests
  ingestion_server/test/env.integration
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#442 Refactor `analytics`
  analytics/Pipfile
  analytics/Pipfile.lock
  analytics/alembic.ini
  analytics/analytics/__init__.py
  analytics/analytics/attribution_worker.py
  analytics/analytics/backdate.py
  analytics/analytics/docs/README.md
  analytics/analytics/docs/__init__.py
  analytics/analytics/docs/redoc.html
  analytics/analytics/docs/schemas/__init__.py
  analytics/analytics/docs/schemas/requests.py
  analytics/analytics/docs/schemas/responses.py
  analytics/analytics/event_controller.py
  analytics/analytics/gen_daily_report.py
  analytics/analytics/migrations/README
  analytics/analytics/migrations/env.py
  analytics/analytics/migrations/script.py.mako
  analytics/analytics/migrations/versions/0cd416f5a7d2_add_attribution_events_table.py
  analytics/analytics/migrations/versions/54e56668b66a_regenerate_initial_migration.py
  analytics/analytics/migrations/versions/7695412f8a64_switch_to_boolean_search_rating_instead_.py
  analytics/analytics/migrations/versions/beb6d39f2dfd_add_reporting_tables.py
  analytics/analytics/models/__init__.py
  analytics/analytics/models/events.py
  analytics/analytics/models/orm.py
  analytics/analytics/models/reports.py
  analytics/analytics/report_controller.py
  analytics/analytics/server.py
  analytics/analytics/settings.py
  analytics/docs/swagger.yaml
  analytics/gunicorn.conf.py
  analytics/server.py
  analytics/settings.py
  analytics/test/all_test.py
  analytics/test/run_test.sh
  ingestion_server/ingestion_server/api.py
  justfile
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#455 Copy operational files into final docker images
  analytics/.dockerignore
  analytics/Dockerfile
  api/.dockerignore
  api/Dockerfile
  docker-compose.yml
  ingestion_server/.dockerignore
  ingestion_server/Dockerfile
  justfile
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#458 Correct docker repository for the ingestion server, update docs
  ingestion_server/README.md
  ingestion_server/docker-compose.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#468 Handle error when audio set does not exist
  api/catalog/api/models/audio.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#469 Publish artifacts with prepended `openverse-` tags
  .github/workflows/ci_cd.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#470 Push tags with `openverse-` prefix
  .github/workflows/ci_cd.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#466 Add logger configuration to allow prod exception handling
  api/catalog/logger.py
  api/catalog/settings.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code

#476 Use the existing and configured env indicator
  api/catalog/settings.py
  api/env.template
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#474 Record transfer limit for data refresh
  ingestion_server/README.md
  ingestion_server/ingestion_server/constants/internal_types.py
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/queries.py
  ingestion_server/test/unit_test.py
  ingestion_server/test/unit_tests/__init__.py
  ingestion_server/test/unit_tests/conftest.py
  ingestion_server/test/unit_tests/test_cleanup.py
  ingestion_server/test/unit_tests/test_es_models.py
  ingestion_server/test/unit_tests/test_queries.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#477 Add environment to data refresh slack alert username
  ingestion_server/ingestion_server/slack.py
  ingestion_server/test/unit_tests/test_slack.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code
