Repository WordPress/openverse-api, pull requests merged in 2022-02, with the labels that each got.

#509 Add quickstart and API documentation to README.md
  README.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#519 Remove pipdeptree
  api/Pipfile
  api/Pipfile.lock
  ingestion_server/Pipfile
  ingestion_server/Pipfile.lock
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#510 Cache waveform data in database
  CONTRIBUTING.md
  api/catalog/api/migrations/0045_audioaddon.py
  api/catalog/api/models/audio.py
  api/catalog/api/utils/waveform.py
  api/catalog/api/views/audio_views.py
  api/test/unit/__init__.py
  api/test/unit/models/__init__.py
  api/test/unit/models/audio_test.py
  justfile
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#507 Run CI/CD on every pull request
  .github/workflows/ci_cd.yml
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#532 Add logging levels to Slack notifications in ingestion server
  ingestion_server/ingestion_server/api.py
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/slack.py
  ingestion_server/ingestion_server/tasks.py
  ingestion_server/test/unit_tests/test_slack.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code
