Repository WordPress/openverse-api, pull requests merged in 2022-03, with the labels that each got.

#530 Django command for generating waveforms
  api/Pipfile
  api/Pipfile.lock
  api/catalog/management/commands/generatewaveforms.py
  api/test/factory/__init__.py
  api/test/factory/faker.py
  api/test/factory/models/__init__.py
  api/test/factory/models/audio.py
  api/test/factory/models/media.py
  api/test/run_test.sh
  api/test/unit/management/__init__.py
  api/test/unit/management/commands/__init__.py
  api/test/unit/management/commands/generatewaveforms_test.py
  api/test/unit/models/audio_test.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx, 💬 talk: discussion

#555 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/label_new_pr.yml
  .github/workflows/pr_label_check.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#563 Send `[]` if media has no tags
  api/catalog/api/serializers/media_serializers.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#566 🔄 Synced file(s) with WordPress/openverse
  .github/workflows/label_new_pr.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#556 Add pronunciation as valid sound category
  api/catalog/api/serializers/audio_serializers.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#568 Add throttle exemptions
  api/Pipfile
  api/Pipfile.lock
  api/catalog/api/utils/throttle.py
  api/test/factory/faker.py
  api/test/factory/models/oauth2.py
  api/test/unit/utils/throttle_test.py
Labels: 🟥 priority: critical, 🌟 goal: addition, 💻 aspect: code

#570 Add missing migrations
  api/catalog/api/migrations/0046_alter_throttledapplication_user.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#577 Remove `query_serializer` for reporting endpoints
  api/catalog/api/docs/audio_docs.py
  api/catalog/api/docs/image_docs.py
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#576 Use `https` for hyperlinked APIs by replacing the URLs
  api/catalog/api/serializers/audio_serializers.py
  api/catalog/api/serializers/base.py
  api/catalog/api/serializers/image_serializers.py
  api/catalog/settings.py
  api/env.docker
  api/env.template
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#584 Replace plural `categories` as field name with singular `category`
  api/test/audio_integration_test.py
  api/test/media_integration.py
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#586 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#583 Replace plural `categories` as field name with singular `category`
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/serializers/audio_serializers.py
  api/catalog/api/serializers/image_serializers.py
  api/test/audio_integration_test.py
  api/test/media_integration.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#590 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#580 Add CI check for uncommitted migrations
  .github/workflows/ci_cd.yml
  justfile
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#591 🔄 Synced file(s) with WordPress/openverse
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#595 Update Black version to latest stable
  .pre-commit-config.yaml
  api/catalog/api/models/media.py
  api/catalog/api/models/mixins.py
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#574 Use `https` for hyperlinked APIs by proxying through NGINX
  api/catalog/api/serializers/base.py
  api/catalog/settings.py
  api/docs/guides/https.md
  api/docs/guides/quickstart.md
  api/env.docker
  api/env.template
  docker-compose.yml
  justfile
  nginx/.gitignore
  nginx/web.conf
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#599 Prevent negative values in waveform data
  api/catalog/api/utils/waveform.py
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code
