Repository WordPress/openverse-api, pull requests merged in 2022-09, with the labels that each got.

#918 Add `peaks` query param for audio requests
  api/catalog/api/examples/audio_responses.py
  api/catalog/api/serializers/audio_serializers.py
  api/catalog/api/views/media_views.py
  api/test/unit/serializers/audio_serializers_test.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#897 Pass user to ingestion-server and indexer_worker containers
  ingestion_server/Dockerfile
  load_sample_data.sh
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#879 Make link validation expiry maximally configurable
  api/catalog/api/utils/validate_images.py
  api/catalog/configuration/link_validation_cache.py
  api/catalog/settings.py
  api/test/unit/configuration/link_validation_cache_test.py
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#868 Move page and page_size query param validation into serializer
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/utils/pagination.py
  api/catalog/api/views/media_views.py
  api/catalog/settings.py
  api/test/auth_test.py
  api/test/dead_link_filter_test.py
  api/test/unit/controllers/test_search_controller.py
  api/test/unit/serializers/media_serializers_test.py
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#902 Uses a terms array to query data
  api/catalog/api/controllers/search_controller.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#939 Add CORS configuration to ES container
  docker-compose.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#934 Make improvements to the oEmbed endpoint
  api/catalog/api/views/image_views.py
  api/test/image_integration_test.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#941 Correct schedule interval comment in dependabot config
  .github/dependabot.yml
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#940 Fix dev API link in README.md
  api/README.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#953 Correct data refresh status message next steps
  ingestion_server/ingestion_server/api.py
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/slack.py
  justfile
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#936 Register audio and image models consistently in admin panel
  api/catalog/api/admin/__init__.py
  api/catalog/api/admin/site.py
  api/catalog/api/examples/audio_responses.py
  api/catalog/api/examples/image_responses.py
  api/catalog/api/migrations/0050_audio_model_plural_names.py
  api/catalog/api/models/audio.py
  api/catalog/api/models/image.py
  api/catalog/api/models/media.py
  api/catalog/api/serializers/media_serializers.py
  api/test/unit/models/media_report_test.py
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code, migrations
