Repository WordPress/openverse-api, pull requests merged in 2022-07, with the labels that each got.

#777 Add request id to logs
  api/Pipfile
  api/Pipfile.lock
  api/catalog/logger.py
  api/catalog/settings.py
Labels: 🟨 priority: medium, 💻 aspect: code, dependencies, 🧰 goal: internal improvement

#771 Removed the "cc-catalog" references from the system-architecure diagram.
  README.md
  readme_assets/system_architecture.png
  readme_assets/system_diagram/README.md
  readme_assets/system_diagram/system_architecture.png
  readme_assets/system_diagram/system_architecture.xml
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#730 Fix search when no filters are applied
  api/catalog/api/controllers/elasticsearch/search.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#779 Add back and correct "resendoauthverification" command
  api/catalog/management/commands/resendoauthverification.py
  api/test/unit/management/commands/resendoauthverification_test.py
Labels: 🟧 priority: high, 🛠 goal: fix, 📄 aspect: text

#790 Add logging and fix all logging contexts
  api/catalog/api/controllers/elasticsearch/related.py
  api/catalog/api/controllers/elasticsearch/search.py
  api/catalog/api/controllers/elasticsearch/stats.py
  api/catalog/api/controllers/elasticsearch/utils.py
  api/catalog/api/utils/oauth2_helper.py
  api/catalog/api/utils/throttle.py
  api/catalog/api/utils/validate_images.py
  api/catalog/api/utils/waveform.py
  api/catalog/api/views/audio_views.py
  api/catalog/api/views/image_views.py
  api/catalog/logger.py
  api/docs/guides/index.md
  api/docs/guides/logging.md
Labels: 🚦 status: awaiting triage

#797 Update action "if" conditionals: check if the PR head belongs to the upstream repo
  .github/workflows/ci_cd.yml
  .github/workflows/pr_closed.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#788 increased token expiry to 12 hours
  api/catalog/settings.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#800 Use envvar for ALLOWED_HOSTS
  api/catalog/settings.py
  api/env.docker
  api/env.template
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#805 Unify header added
  README.md
Labels: 🟨 priority: medium, 📄 aspect: text, 🧰 goal: internal improvement

#707 Separate go-live step from indexing
  ingestion_server/Pipfile
  ingestion_server/Pipfile.lock
  ingestion_server/env.docker
  ingestion_server/env.template
  ingestion_server/ingestion_server/api.py
  ingestion_server/ingestion_server/constants/media_types.py
  ingestion_server/ingestion_server/distributed_reindex_scheduler.py
  ingestion_server/ingestion_server/elasticsearch_models.py
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/ingestion_server/indexer_worker.py
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/queries.py
  ingestion_server/ingestion_server/tasks.py
  ingestion_server/test/env.integration
  ingestion_server/test/gen_integration_compose.py
  ingestion_server/test/integration_test.py
  ingestion_server/test/test_constants.py
  justfile
  load_sample_data.sh
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#712 Make the index names configurable using env vars
  .flake8
  api/catalog/api/constants/media_types.py
  api/catalog/api/models/models.py
  api/catalog/api/views/audio_views.py
  api/catalog/api/views/image_views.py
  api/catalog/configuration/__init__.py
  api/catalog/configuration/aws.py
  api/catalog/configuration/elasticsearch.py
  api/catalog/configuration/logging.py
  api/catalog/settings.py
  api/env.template
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#792 Remove bespoke throttle exemption
  api/catalog/api/migrations/0048_alter_throttledapplication_rate_limit_model.py
  api/catalog/api/models/oauth.py
  api/catalog/api/utils/oauth2_helper.py
  api/catalog/api/utils/throttle.py
  api/catalog/settings.py
  api/docs/reference/api/authentication_and_throttling.md
  api/docs/reference/api/index.rst
  api/test/unit/management/commands/resendoauthverification_test.py
  api/test/unit/utils/throttle_test.py
  justfile
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#801 Add trailing slashes to URL conf paths
  api/catalog/api/views/oauth2_views.py
  api/catalog/urls/__init__.py
  api/catalog/urls/auth_tokens.py
  api/test/api_live_integration.py
  api/test/auth_test.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#808 Fix related media endpoint
  api/catalog/api/controllers/elasticsearch/related.py
  api/catalog/api/controllers/elasticsearch/search.py
  api/test/audio_integration_test.py
  api/test/image_integration_test.py
  api/test/media_integration.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#810 Recombine divergent leaf nodes using migration
  api/catalog/api/migrations/0049_merge_migrations_number_48.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#816 Update contribution link in API docs to point to CONTRIBUTING.md
  api/catalog/api/docs/README.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text

#815 Fix missing rate limit model from rate_limit info endpoint
  api/catalog/api/views/oauth2_views.py
  api/test/auth_test.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#814 Add thumbnails staging deployment
  .github/actions/staging-thumbnails-deploy/action.yml
  .github/workflows/build_imaginary.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#818 Fix if condition for thumbnails build/deploy
  .github/workflows/build_imaginary.yml
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#714 Add task for deleting indices
  ingestion_server/ingestion_server/api.py
  ingestion_server/ingestion_server/es_helpers.py
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/ingestion_server/indexer_worker.py
  ingestion_server/ingestion_server/tasks.py
  ingestion_server/test/integration_test.py
Labels: 🟧 priority: high, 🌟 goal: addition, 💻 aspect: code

#825 Bump sentry-sdk from 1.6.0 to 1.9.0
  api/Pipfile.lock
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement
