Repository WordPress/openverse-api, pull requests merged in 2022-10, with the labels that each got.

#964 Use MoreLikeThis ES class for similar search in seach controller
  api/catalog/api/controllers/search_controller.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#922 Adding shellcheck to openverse-api
  .pre-commit-config.yaml
  api/test/run_test.sh
  ingestion_server/test/run_test.sh
  ingestion_server/test/update_mocks.sh
  load_sample_data.sh
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#966 Update of the old CC BASE_URL of media reports
  api/catalog/api/models/media.py
  api/catalog/settings.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#932 Catch struct errors in `watermark/` endpoint
  api/catalog/api/utils/watermark.py
  api/env.docker
  api/test/unit/utils/watermark_test.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 🕹 aspect: interface

#938 Use the scaled-down image for SMK thumbnails
  api/catalog/api/views/image_views.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#981 Allow more than one argument to recipe `up`
  justfile
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#982 Count thumbnail timeouts per domain
  api/catalog/api/views/media_views.py
  api/catalog/settings.py
  api/env.template
  api/test/unit/views/media_views_test.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#985 Upgrade Django from 4.1.0 to 4.1.2 for security fix
  api/Pipfile
  api/Pipfile.lock
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#987 Remove SourceLogo
  api/catalog/api/admin/__init__.py
  api/catalog/api/migrations/0051_delete_sourcelogo.py
  api/catalog/api/models/__init__.py
  api/catalog/api/models/models.py
  api/catalog/api/serializers/provider_serializers.py
  api/catalog/settings.py
Labels: migrations

#989 Pin dependencies in `Pipfile`
  api/Pipfile
  api/Pipfile.lock
  ingestion_server/Pipfile
  ingestion_server/Pipfile.lock
Labels: 🟧 priority: high, 🤖 aspect: dx, 🧰 goal: internal improvement
