Repository WordPress/openverse-api, pull requests merged in 2022-12, with the labels that each got.

#1043 Use environment variable to determine whether to filter dead links by default; fix flaky tests
  api/catalog/api/serializers/media_serializers.py
  api/catalog/settings.py
  api/env.docker
  api/env.template
  api/test/audio_integration_test.py
  api/test/auth_test.py
  api/test/media_integration.py
  api/test/search_qa.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#1033 Update default accuracy to None to support null JSON values
  api/catalog/api/examples/audio_responses.py
  api/catalog/api/examples/image_responses.py
  api/catalog/api/serializers/media_serializers.py
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#1027 Replace grequests with asyncio solution
  api/Pipfile
  api/Pipfile.lock
  api/catalog/api/utils/validate_images.py
  api/test/dead_link_filter_test.py
  api/test/unit/utils/validate_images_test.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#1051 Handle `asyncio.TimeoutError` for link validation code
  api/catalog/api/utils/validate_images.py
  api/test/unit/utils/validate_images_test.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1045 Use pre-commit from `.pyz` executable
  .gitignore
  api/Pipfile
  api/Pipfile.lock
  justfile
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#1053 Delete resendoauthverification and resendoauthverification tests
  api/catalog/management/commands/resendoauthverification.py
  api/test/unit/management/commands/resendoauthverification_test.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#1013 Add db connection commands and non-root user for `web` container
  .github/workflows/ci_cd.yml
  api/Dockerfile
  api/Pipfile
  api/Pipfile.lock
  docker-compose.yml
  justfile
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1055 Fix permissions when building docs
  .github/workflows/ci_cd.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#1040 Reduce DB queries needed in search results
  api/catalog/api/admin/__init__.py
  api/catalog/api/admin/site.py
  api/catalog/api/examples/audio_responses.py
  api/catalog/api/examples/image_responses.py
  api/catalog/api/migrations/0052_relational_fields.py
  api/catalog/api/models/audio.py
  api/catalog/api/models/image.py
  api/catalog/api/models/media.py
  api/catalog/api/serializers/audio_serializers.py
  api/catalog/api/serializers/image_serializers.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/views/audio_views.py
  api/catalog/api/views/image_views.py
  api/catalog/api/views/media_views.py
  api/test/dead_link_filter_test.py
  api/test/media_integration.py
  api/test/unit/models/media_report_test.py
  api/test/unit/views/media_views_test.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code, migrations

#1059 Add hash for `livereload` wheel
  api/Pipfile.lock
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1062 Added coreutils to the pre-requisites
  CONTRIBUTORS.md
  api/docs/guides/quickstart.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text
