Repository WordPress/openverse-api, pull requests merged in 2022-11, with the labels that each got.

#1002 Fix URL in API consumer docs
  api/catalog/api/docs/README.md
  api/catalog/api/models/models.py
  api/catalog/urls/__init__.py
Labels: 🟧 priority: high, 🛠 goal: fix, 📄 aspect: text

#1006 Unify pre-commit config across repos
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  api/catalog/api/constants/field_order.py
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/models/audio.py
  api/catalog/api/models/image.py
  api/catalog/api/models/media.py
  api/catalog/api/utils/attribution.py
  api/catalog/api/utils/ccrel.py
  api/catalog/api/utils/dead_link_mask.py
  api/catalog/api/utils/help_text.py
  api/catalog/api/utils/licenses.py
  api/catalog/api/utils/waveform.py
  api/catalog/configuration/elasticsearch.py
  api/catalog/configuration/link_validation_cache.py
  api/catalog/urls/swagger.py
  api/test/api_live_integration.py
  api/test/api_live_search_qa.py
  api/test/dead_link_filter_test.py
  api/test/media_integration.py
  api/test/search_qa.py
  api/test/unit/controllers/test_search_controller.py
  api/test/unit/utils/validate_images_test.py
  api/test/unit/utils/watermark_test.py
  api/test/unit/utils/waveform_test.py
  api/test/unit/views/image_views_test.py
  api/test/unit/views/media_views_test.py
  ingestion_server/ingestion_server/es_helpers.py
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/queries.py
  ingestion_server/ingestion_server/tasks.py
  ingestion_server/test/gen_integration_compose.py
  ingestion_server/test/integration_test.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#1007 Fix link to audio/image details page in Django admin
  api/catalog/api/models/image.py
  api/catalog/api/models/media.py
  api/env.docker
  api/env.template
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1008 Added link for automated tests files in DOCUMENTATION_GUIDELINES.md
  DOCUMENTATION_GUIDELINES.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#990 Add Nginx target to API Dockerfile
  .github/workflows/ci_cd.yml
  api/.dockerignore
  api/.gitignore
  api/Dockerfile
  api/catalog/settings.py
  api/nginx.conf.template
  docker-compose.yml
  justfile
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1009 Various improvements to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text

#1015 Allow `/version` to be defined by environment variables
  api/Dockerfile
  api/nginx.conf.template
  justfile
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code, 🐳 tech: docker

#1014 Add `api-nginx` to options for docker image push action
  .github/workflows/push_docker_image.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text

#1012 Make quoted queries behave as described in the API documentation (return exact matches only)
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/examples/audio_requests.py
  api/catalog/api/examples/image_requests.py
  api/test/audio_integration_test.py
  api/test/image_integration_test.py
  api/test/media_integration.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
