Repository WordPress/openverse-api, pull requests merged in 2022-04, with the labels that each got.

#598 Add CSRF trusted origins setting
  api/catalog/settings.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 🕹 aspect: interface

#618 Remove analytics server
  .github/dependabot.yml
  .github/workflows/ci_cd.yml
  README.md
  analytics/.dockerignore
  analytics/Dockerfile
  analytics/Pipfile
  analytics/Pipfile.lock
  analytics/README.md
  analytics/alembic.ini
  analytics/analytics/__init__.py
  analytics/analytics/attribution_worker.py
  analytics/analytics/backdate.py
  analytics/analytics/docs/README.md
  analytics/analytics/docs/__init__.py
  analytics/analytics/docs/redoc.html
  analytics/analytics/docs/schemas/__init__.py
  analytics/analytics/docs/schemas/requests.py
  analytics/analytics/docs/schemas/responses.py
  analytics/analytics/event_controller.py
  analytics/analytics/gen_daily_report.py
  analytics/analytics/migrations/README
  analytics/analytics/migrations/env.py
  analytics/analytics/migrations/script.py.mako
  analytics/analytics/migrations/versions/0cd416f5a7d2_add_attribution_events_table.py
  analytics/analytics/migrations/versions/54e56668b66a_regenerate_initial_migration.py
  analytics/analytics/migrations/versions/7695412f8a64_switch_to_boolean_search_rating_instead_.py
  analytics/analytics/migrations/versions/beb6d39f2dfd_add_reporting_tables.py
  analytics/analytics/models/__init__.py
  analytics/analytics/models/events.py
  analytics/analytics/models/orm.py
  analytics/analytics/models/reports.py
  analytics/analytics/report_controller.py
  analytics/analytics/server.py
  analytics/analytics/settings.py
  analytics/env.docker
  analytics/env.template
  analytics/gunicorn.conf.py
  analytics/test/all_test.py
  analytics/test/run_test.sh
  api/docs/guides/quickstart.md
  docker-compose.yml
  justfile
  load_sample_data.sh
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#626 Fix install script for no more analytics
  justfile
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#628 Specify service when running test recipe
  justfile
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#593 Accurately report status of data_refresh when work is distributed
  ingestion_server/ingestion_server/api.py
  ingestion_server/ingestion_server/distributed_reindex_scheduler.py
  ingestion_server/ingestion_server/indexer.py
  ingestion_server/ingestion_server/indexer_worker.py
  ingestion_server/ingestion_server/state.py
  ingestion_server/ingestion_server/tasks.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#564 Add a timeout to the `@_loop` recipe
  justfile
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#634 Make Exempi library optional for local setup
  api/Dockerfile
  api/catalog/api/views/image_views.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#627 Reduce flakiness of `just init`
  ingestion_server/ingestion_server/ingest.py
  ingestion_server/ingestion_server/queries.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#637 Fix bug in the URL scheme rewrite
  api/catalog/api/serializers/base.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#639 Prune and narrow `# noqa` comments
  DOCUMENTATION_GUIDELINES.md
  api/catalog/api/docs/audio_docs.py
  api/catalog/api/docs/image_docs.py
  api/catalog/api/docs/media_docs.py
  api/catalog/api/examples/audio_requests.py
  api/catalog/api/examples/audio_responses.py
  api/catalog/api/examples/image_requests.py
  api/catalog/api/examples/image_responses.py
  api/catalog/api/views/oauth2_views.py
  api/catalog/example_responses.py
  api/catalog/logger.py
  api/catalog/settings.py
  api/docs/conf.py
  api/test/examples_test.py
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text

#636 Add manually triggered action for pushing docker image by SHA
  .github/workflows/push_docker_image.yml
  api/docs/guides/index.md
  api/docs/guides/publish.md
  api/docs/guides/test.md
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#641 Add a workflow to build our custom image for imaginary
  .github/workflows/build_imaginary.yml
  docker-compose.yml
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#630 Improve the thumbnail service to support compression and WEBP
  .github/workflows/build_imaginary.yml
  api/catalog/api/docs/audio_docs.py
  api/catalog/api/docs/image_docs.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/views/audio_views.py
  api/catalog/api/views/image_views.py
  api/catalog/api/views/media_views.py
  api/catalog/settings.py
  api/docs/guides/quickstart.md
  api/env.docker
  api/env.template
  api/test/audio_integration_test.py
  api/test/image_integration_test.py
  api/test/media_integration.py
  docker-compose.yml
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code

#647 Update bimg version in imaginary Docker image
  .github/workflows/build_imaginary.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#644 Fix tracking of data refresh progress
  ingestion_server/ingestion_server/api.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#645 Tag on-demand image by specified commit
  .github/workflows/push_docker_image.yml
  api/docs/_static/publish_action_example.png
  api/docs/guides/publish.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#589 Move media type categories to constants module
  api/catalog/api/constants/field_values.py
  api/catalog/api/serializers/audio_serializers.py
  api/catalog/api/serializers/image_serializers.py
  api/catalog/api/serializers/media_serializers.py
  api/catalog/api/utils/help_text.py
  api/test/audio_integration_test.py
  api/test/unit/utils/test_help_text.py
Labels: 🚦 status: awaiting triage

#638 Add step to run Django check in CI
  .github/workflows/ci_cd.yml
  justfile
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#651 Change default email port to 587
  api/catalog/settings.py
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement
