Repository WordPress/openverse-api, pull requests merged in 2023-02, with the labels that each got.

#1113 Tally top 80 results exactly and fix "monday" timestamp calculation
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/utils/tallies.py
  api/test/unit/controllers/test_search_controller.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1114 Add staging deployment action for the API
  .github/actions/staging-deploy/action.yml
  .github/workflows/ci_cd.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1132 Handle tally cases where `results` is `None`
  api/catalog/api/controllers/search_controller.py
  api/test/unit/controllers/test_search_controller.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#1125 Include image tag in built image
  .github/workflows/ci_cd.yml
  api/Dockerfile
  docker-compose.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1082 Add zero-downtime deployments & data transformations guide
  api/docs/guides/zero-downtime-database-management.md
Labels: 🟩 priority: low, 🌟 goal: addition, 📄 aspect: text

#1142 Add API rollback workflow
  .github/workflows/api-rollback.yml
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx

#1144 Add screen to API Docker image
  api/Dockerfile
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1147 Monorepo archive notice
  README.md
Labels: 🟧 priority: high, 🌟 goal: addition, 🤖 aspect: dx
