Repository WordPress/openverse-api, pull requests merged in 2023-01, with the labels that each got.

#1057 Remove references to the upstream database in the API
  api/catalog/settings.py
  api/env.docker
  api/env.template
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#1047 Add ES healthchecks to `/healthcheck/` endpoint
  api/catalog/api/views/health_views.py
  api/test/unit/conftest.py
  api/test/unit/views/health_views_test.py
  api/test/unit/views/image_views_test.py
  api/test/unit/views/media_views_test.py
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#1050 Add Search Algorithm page to API docs
  api/docs/reference/index.rst
  api/docs/reference/search_algorithm.md
Labels: 🟩 priority: low, 📄 aspect: text, 🧰 goal: internal improvement

#1035 Update copyright holder in license
  LICENSE
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text, ⛔ status: blocked

#1056 Switch to Photon for thumbnail generation
  .github/actions/staging-thumbnails-deploy/action.yml
  .github/workflows/build_imaginary.yml
  api/catalog/api/models/mixins.py
  api/catalog/api/utils/photon.py
  api/catalog/api/views/media_views.py
  api/catalog/settings.py
  api/docs/guides/quickstart.md
  api/env.docker
  api/env.template
  api/test/unit/conftest.py
  api/test/unit/utils/conftest.py
  api/test/unit/utils/photon_test.py
  api/test/unit/utils/validate_images_test.py
  api/test/unit/views/media_views_test.py
  docker-compose.yml
  justfile
Labels: 🟩 priority: low, 🕹 aspect: interface, 🧰 goal: internal improvement

#1032 Make page_count self-truncating when we detect the last page of a query
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/examples/audio_responses.py
  api/catalog/api/examples/image_responses.py
  api/test/unit/controllers/test_search_controller.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#1080 Forward SSL status of upstream image URL to Photon
  api/catalog/api/utils/photon.py
  api/test/unit/utils/photon_test.py
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code

#1087 Update `dependabot.yml` to make Dependabot update GitHub actions
  .github/dependabot.yml
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#1088 Tally provider occurrences in results
  api/Pipfile
  api/Pipfile.lock
  api/catalog/api/controllers/search_controller.py
  api/catalog/api/utils/tallies.py
  api/catalog/settings.py
  api/test/unit/conftest.py
  api/test/unit/controllers/test_search_controller.py
  api/test/unit/serializers/media_serializers_test.py
  api/test/unit/utils/tallies_test.py
  api/test/unit/utils/throttle_test.py
Labels: 🟧 priority: high, ✨ goal: improvement, 💻 aspect: code
